name: joincap
version: git
version-script: |
  echo $(git describe --tags $(git rev-list --tags --max-count=1))-$(git log --oneline | head -1 | awk '{print $1}')
summary: Merge multiple pcap files together, gracefully.
description: |
  Merge multiple pcap files together, gracefully.

grade: stable
confinement: strict

parts:
  joincap:
    source: .
    plugin: go
    go-importpath: github.com/assafmo/joincap

apps:
  joincap:
    command: joincap